name: Shimmo
main: dev.shiron.shimmo.Shimmo
version: 1.0.0
api-version: 1.19
softdepend: [ HolographicDisplays ]
commands:
  menu:
    description: Open menu
    usage: /<command>
    permission: shimmo.core.menu